export type ElementSize = 'xs' | 'sm' | 'md' | 'lg'
export type ElementColor =
  | 'default'
  | 'neutral'
  | 'primary'
  | 'secondary'
  | 'accent'
  | 'info'
  | 'success'
  | 'warning'
  | 'error'
  | 'ghost'
export type ElementVariant = 'contain' | 'outline'
